name: CI

on:
  push:

jobs:
  build-and-test:
    name: build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
      - uses: cachix/cachix-action@v15
        with:
          name: xbar-pr-status
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build --print-build-logs
