name: Update Nix

on:
  schedule:
    - cron: "0 12 * * 1"
  # TEMP
  push:
    branches: [update-nix-automatically]

jobs:
  update-nix:
    name: Update Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - run: nix flake update
      - run: git checkout -b update-nix-$(date -I)
      - run: git commit --all --message "update Nix sources" --author "GitHub Actions"
      - run: gh pr create --title "update Nix sources, $(date -I)"
